server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: jkkscent123
    url: jdbc:mysql://localhost:3306/jkkscent?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: jkkscent
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true